# Generated by Django 3.2.3 on 2022-05-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador unico del carrito')),
                ('total', models.IntegerField(verbose_name='total del carrito')),
                ('fechaCarrito', models.DateField(verbose_name='fecha del carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de la categoria')),
                ('nombreCategoria', models.CharField(max_length=25, verbose_name='nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutCli', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='Run del usuario')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre o nombres del usuario')),
                ('apellido', models.CharField(max_length=20, verbose_name='apellido o apellidos del usuario')),
                ('email', models.CharField(max_length=50, verbose_name='Email del usuario')),
                ('contra', models.CharField(max_length=12, verbose_name='contraseña del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de comuna')),
                ('nomComuna', models.CharField(max_length=20, verbose_name='Nombre de la comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador unico de la marca')),
                ('nombreMarca', models.CharField(max_length=20, verbose_name='Nombre de la marca')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False, verbose_name='id de la region')),
                ('nomRegion', models.CharField(max_length=20, verbose_name='nombre de la region')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('idTienda', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador unico de la tienda')),
                ('direccion', models.CharField(max_length=30, verbose_name='direccion de la tienda')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUs', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificadot del tipo de usuario')),
                ('nomTipoUs', models.CharField(max_length=30, verbose_name='Tipo de usuario establecido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProd', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador unico del producto')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre del producto')),
                ('stock', models.IntegerField(verbose_name='cantidad del producto')),
                ('precio', models.IntegerField(verbose_name='precio unitario del producti')),
                ('codigo', models.CharField(max_length=5, verbose_name='debe ser dos letras en mayuscula y tres numeros ej: LS123')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.marca')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False, verbose_name='id del pedido realizado por la bodega a la empresa')),
                ('nomPedido', models.CharField(max_length=20, verbose_name='nombre del producto pedido')),
                ('cantidad', models.IntegerField(verbose_name='cantidad del producto solicitado')),
                ('codigoProducto', models.CharField(max_length=5, verbose_name=' 2 letras 3 numeros ej: LS123')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialVentas',
            fields=[
                ('idHistorial', models.AutoField(primary_key=True, serialize=False, verbose_name='identifiador del historial')),
                ('total', models.IntegerField(verbose_name='total de la venta realizada')),
                ('fecha', models.DateField(verbose_name='fecha de la venta realizada')),
                ('run', models.CharField(max_length=14, verbose_name='rut del usuario que realizo la compra')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador de la direccion')),
                ('domicilio', models.CharField(max_length=40, verbose_name='direccion del domicilio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.cliente')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipousuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.tipousuario'),
        ),
        migrations.CreateModel(
            name='CarritoPro',
            fields=[
                ('idCarritoPro', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador de carrito clase intermedia')),
                ('cantidad', models.IntegerField(verbose_name='cantidad de unidades del producto pedido')),
                ('precioUnidad', models.IntegerField(verbose_name='precio unitario del producto')),
                ('subtotal', models.IntegerField(verbose_name='la multiplicacion del precio unitario con la cantidad de productos solicitados')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.cliente'),
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('idBodega', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador de la bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.producto')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_pro.tienda')),
            ],
        ),
    ]
