# Generated by Django 3.2.3 on 2022-05-15 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music_pro.tienda'),
            preserve_default=False,
        ),
    ]
