# Generated by Django 3.2.3 on 2022-06-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_pro', '0002_producto_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='bodega',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='cantidad del producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(null=True, upload_to='instru'),
        ),
    ]
