# Generated by Django 3.2.3 on 2022-06-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_pro', '0004_auto_20220609_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tienda',
        ),
    ]
