# Generated by Django 3.2.3 on 2022-06-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_pro', '0005_remove_producto_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='codigoProducto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='idProducto',
            field=models.IntegerField(default=1, max_length=5, verbose_name='id del producto'),
            preserve_default=False,
        ),
    ]
